// Validation and hashing for galley notes — the inline editorial review
// described in CLAUDE.md. Shared by the write endpoint (src/pages/api/galley.ts)
// and the pull script (scripts/galley-pull.mjs), which is the point: the code
// that accepts a note is the code that later reads it back.
//
// Plain JS for the same reason as csp.js, schedule.js, and preview.js — one
// module has to run in the Cloudflare Worker, under `node --test`, and in a
// vanilla Node script, with no TypeScript tooling on two of those three sides.

/**
 * Field size caps. Generous enough for a real editorial note (a few
 * paragraphs) and small enough that a row can't be used as free storage.
 *
 * `body` and `suggestion` are the only fields a person types freely; the rest
 * are machine-generated by the review client, so their caps are tight enough
 * to reject anything obviously wrong without being worth tuning.
 */
export const LIMITS = {
  body: 4000,
  suggestion: 4000,
  quote: 1000,
  context: 200,
};

/** The kinds of note a reviewer can leave. Mirrors the CHECK on galley_notes.kind. */
export const KINDS = new Set(['comment', 'suggestion']);

/**
 * Slug and reviewer shape. Kept identical to preview.js's SLUG_RE rather than
 * imported, because these two modules are deliberately independent — galley.js
 * is about note contents and preview.js is about authorisation, and a change
 * to one should not silently widen the other. The pairing is asserted in the
 * tests.
 */
const ID_RE = /^[a-z0-9-]+$/;

/** `"42-47"` → `{ start: 42, end: 47 }`, else null. */
export function parseSrc(src) {
  if (typeof src !== 'string') return null;
  const m = /^(\d{1,7})-(\d{1,7})$/.exec(src);
  if (!m) return null;
  const start = Number(m[1]);
  const end = Number(m[2]);
  // A backwards range means the anchor was hand-edited; there is no sensible
  // way to apply it, so treat it as absent rather than guessing.
  if (start < 1 || end < start) return null;
  return { start, end };
}

/**
 * SHA-256 of a string, lowercase hex.
 *
 * Used for the revision hash recorded on every note. Callers MUST hash the
 * ENTIRE .mdx file, frontmatter included — not just the post body. Anchors are
 * absolute line numbers in the file, so adding a single tag to the frontmatter
 * shifts every one of them while leaving the prose untouched. A body-only hash
 * would call that "unchanged" and silently hand the pull script line numbers
 * pointing one line off, which is precisely the failure the hash exists to
 * catch.
 *
 * @param {string} text
 * @returns {Promise<string>}
 */
export async function sha256Hex(text) {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Distinguishes "too long" from "absent". Both would otherwise collapse to
 * null and an oversize note would be reported as a missing one.
 */
const TOO_LONG = Symbol('too-long');

/**
 * Trim a field. Absent, non-string, and empty all become null; anything over
 * `max` becomes TOO_LONG.
 *
 * Oversize input is rejected rather than truncated: a note that comes back
 * with its last paragraph silently missing is worse than one that failed
 * loudly while the editor still had it on screen.
 */
function clean(value, max) {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  if (trimmed.length === 0) return null;
  if (trimmed.length > max) return TOO_LONG;
  return trimmed;
}

/**
 * Validate a note submitted by the review client.
 *
 * Returns a normalised note ready to insert, or an error code the endpoint
 * turns into a 400. Never throws — the caller is a request handler, and a
 * malformed body is an expected input rather than an exceptional one.
 *
 * Note that `slug` is validated for SHAPE only. Whether the reviewer is
 * authorised for that slug is an authorisation question, answered by comparing
 * against the signed grant in the endpoint — never here.
 *
 * @param {unknown} input parsed JSON body
 * @returns {{ ok: true, note: object } | { ok: false, error: string }}
 */
export function validateNote(input) {
  if (typeof input !== 'object' || input === null) return { ok: false, error: 'invalid_body' };

  const { slug, kind = 'comment', src, quote, prefix, suffix, body, suggestion } = input;

  if (typeof slug !== 'string' || !ID_RE.test(slug)) return { ok: false, error: 'invalid_slug' };
  if (typeof kind !== 'string' || !KINDS.has(kind)) return { ok: false, error: 'invalid_kind' };

  const fields = {
    body: clean(body, LIMITS.body),
    suggestion: clean(suggestion, LIMITS.suggestion),
    quote: clean(quote, LIMITS.quote),
    prefix: clean(prefix, LIMITS.context),
    suffix: clean(suffix, LIMITS.context),
  };
  for (const [name, value] of Object.entries(fields)) {
    if (value === TOO_LONG) return { ok: false, error: `${name}_too_long` };
  }

  // A comment is its prose. A suggestion is its replacement text, and the
  // prose explaining it is optional — an editor proposing better wording has
  // often said everything they mean by writing it.
  if (kind === 'comment' && fields.body === null) return { ok: false, error: 'body_required' };
  if (kind === 'suggestion' && fields.suggestion === null) {
    return { ok: false, error: 'suggestion_required' };
  }

  // An absent anchor is allowed — it is how a whole-draft note is recorded.
  // A malformed one is not: it would put a bogus line number in front of
  // whoever applies the note.
  const hasSrc = src !== undefined && src !== null && src !== '';
  const range = hasSrc ? parseSrc(src) : null;
  if (hasSrc && range === null) return { ok: false, error: 'invalid_src' };

  return {
    ok: true,
    note: {
      slug,
      kind,
      srcStart: range?.start ?? null,
      srcEnd: range?.end ?? null,
      quote: fields.quote,
      prefix: fields.prefix,
      suffix: fields.suffix,
      body: fields.body,
      suggestion: fields.suggestion,
    },
  };
}
