import { defineMiddleware } from 'astro:middleware';
import { CSP } from './lib/csp.js';
import { SECURITY_HEADERS } from './lib/security-headers.js';
import { isPreviewHost, verifyPreviewGrant } from './lib/preview.js';
import { isLinkActive } from './lib/preview-links.js';
import { verifyAccessJwt } from './lib/access.js';
import { isAdminPath } from './lib/admin-path.js';
import { tryGetEnv } from './lib/server.ts';

// Applies response-level headers to every response generated by the Astro
// worker. dist/client/_headers (generated post-build by scripts/gen-headers.mjs)
// covers static asset responses served via the Cloudflare ASSETS binding,
// but on-demand routes (every page in this site, plus /blog/rss.xml and
// /api/*) generate their responses through the Worker and bypass _headers
// entirely.
//
// CSP value lives in src/lib/csp.js and the rest of the set in
// src/lib/security-headers.js, so middleware + generator share one source.
// Cache-Control defaults to 1h so the edge cache absorbs traffic while still
// letting the dynamic edition line refresh hourly; routes can override by
// setting the header before middleware runs (e.g. prerendered 404 emits
// max-age=0 from Astro).
//
// The non-CSP security headers apply to EVERY worker response, not just
// HTML. /blog/rss.xml is the reason: it renders on-demand for scheduled
// publishing, so it is no longer served by the ASSETS binding and would
// otherwise inherit no security headers at all. They are applied only when
// absent, so a route that picked a stricter value keeps it — /api/*
// responses from src/lib/server.ts send `Referrer-Policy: no-referrer` and
// `Cache-Control: no-store`, which must not be widened to the defaults.

// Scheduled-post preview unlocks are resolved here, before the route runs, and
// handed to routes via locals. Two independent signals (see src/lib/preview.js):
// the *.workers.dev host check reveals every scheduled post on PR-branch
// deploys, while a signed link reveals exactly the one post it names. Both
// default to closed, so any failure to resolve them hides drafts.
//
// A signed link is checked twice: the signature, and then the preview_links
// allowlist that makes it revocable. Both happen only when a `?preview=` token
// is actually present — the normal request path does no HMAC work and touches
// no database, which is what the `if (token)` guard below is protecting.

// isLinkActive — the allowlist lookup that makes a link revocable — lives in
// src/lib/preview-links.js. It is plain JS purely so `node --test` can reach its
// fail-closed branches (no binding, a store that throws), which are the ones
// smoke cannot exercise over HTTP and which nothing was checking while it sat
// in this file. See src/lib/preview-links.test.js.

// The Desk (/admin) is gated HERE rather than in its routes, so there is one
// place to read and one place to get wrong. Cloudflare Access already stands in
// front of these paths at the edge; this is the second check, for the same
// reason `workers_dev: false` is paired with isPreviewHost excluding the
// production alias. See src/lib/access.js for why `aud` is the load-bearing
// claim, and src/lib/admin-path.js for why the path test is not a startsWith.
//
// A failure 404s rather than 403s. /admin existing at all is a fact worth not
// confirming, and it matches how a scheduled post behaves without a token —
// this codebase's answer to "you may not see this" is already "there is nothing
// here".

export const onRequest = defineMiddleware(async (context, next) => {
  const admin = isAdminPath(context.url.pathname);
  if (admin) {
    const env = tryGetEnv();
    // Access sends the JWT in a header and, for browser navigations, also in a
    // cookie. The header is the one to read: it is set by the edge on every
    // proxied request and cannot be forged past it, whereas parsing the cookie
    // would mean trusting a value a browser can be talked into sending.
    const grant = await verifyAccessJwt(context.request.headers.get('Cf-Access-Jwt-Assertion'), {
      teamDomain: env?.ACCESS_TEAM_DOMAIN,
      aud: env?.ACCESS_AUD,
      jwksOverride: env?.ACCESS_JWKS_OVERRIDE,
    });
    if (!grant) {
      // Built here rather than deferred to the 404 route, because rendering that
      // route would run the rest of this pipeline for a request already refused.
      return new Response('Not found', {
        status: 404,
        headers: {
          ...SECURITY_HEADERS,
          'Content-Type': 'text/plain; charset=utf-8',
          'Cache-Control': 'no-store',
          'X-Robots-Tag': 'noindex, nofollow',
        },
      });
    }
    context.locals.admin = grant;
  }

  const showScheduled = isPreviewHost(context.url.hostname);

  // Only touch the crypto when a token is actually present — the normal
  // request path does no HMAC work at all.
  const token = context.url.searchParams.get('preview');
  let previewSlug: string | null = null;
  let previewReviewer: string | null = null;
  if (token) {
    // One env read for the whole feature. tryGetEnv returns null outside the
    // worker runtime rather than throwing, so an unavailable binding fails
    // closed instead of 500ing the route.
    const env = tryGetEnv();
    const grant = await verifyPreviewGrant(token, env?.PREVIEW_SIGNING_KEY);
    // A valid signature is necessary but not sufficient: the link must also
    // still be in the allowlist. Revocation deliberately takes READING as well
    // as writing — both locals stay null, so the post 404s. Taking a draft back
    // from someone should take the draft, not just the comment box.
    if (grant && (await isLinkActive(env?.DB, grant.linkId))) {
      previewSlug = grant.slug;
      // Only a token that names a reviewer authorises leaving galley notes. A
      // view-only link resolves this to null, and /api/galley refuses to write
      // without it — so the ability to comment is carried by the signature, not
      // by anything the reader can change.
      previewReviewer = grant.reviewer;
    }
  }

  context.locals.showScheduled = showScheduled;
  context.locals.previewSlug = previewSlug;
  context.locals.previewReviewer = previewReviewer;

  const response = await next();
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    if (!response.headers.has(name)) response.headers.set(name, value);
  }
  const contentType = response.headers.get('content-type') ?? '';
  if (contentType.includes('text/html')) {
    response.headers.set('Content-Security-Policy', CSP);
    if (!response.headers.has('Cache-Control')) {
      response.headers.set('Cache-Control', 'public, max-age=3600');
    }
  }

  // A response that may contain an unpublished post must never be cached or
  // indexed. These two OVERRIDE rather than set-if-absent — the only place in
  // this file that does — because the values already present are exactly the
  // ones we're protecting against (`max-age=3600` from the block above, and
  // the RSS route's own Cache-Control at src/pages/blog/rss.xml.ts).
  //
  // The Desk is in this set for a stronger version of the same reason. A preview
  // link exposes one draft; /admin lists every draft, every reviewer label and
  // every note at once, so a cached copy at the edge would be the whole
  // inventory sitting in shared storage.
  if (showScheduled || previewSlug || admin) {
    response.headers.set('Cache-Control', 'no-store');
    response.headers.set('X-Robots-Tag', 'noindex, nofollow');
  }

  return response;
});
