import { defineMiddleware } from 'astro:middleware';
import { CSP } from './lib/csp.js';

// Applies response-level headers to every HTML response generated by the
// Astro worker. public/_headers (generated post-build by scripts/gen-headers.mjs)
// covers static asset responses served via the Cloudflare ASSETS binding,
// but on-demand routes (every HTML page in this site) generate their
// responses through the Worker and bypass _headers entirely.
//
// CSP value lives in src/lib/csp.js so middleware + generator share one
// source. Cache-Control defaults to 1h so the edge cache absorbs traffic
// while still letting the dynamic edition line refresh hourly; routes can
// override by setting the header before middleware runs (e.g. prerendered
// 404 emits max-age=0 from Astro).

export const onRequest = defineMiddleware(async (context, next) => {
  const response = await next();
  const contentType = response.headers.get('content-type') ?? '';
  if (contentType.includes('text/html')) {
    response.headers.set('Content-Security-Policy', CSP);
    if (!response.headers.has('Cache-Control')) {
      response.headers.set('Cache-Control', 'public, max-age=3600');
    }
  }
  return response;
});
